version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: support-ticket-postgres
    environment:
      POSTGRES_DB: support_ticket_db
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: support_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./support-ticket-system-backend   
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/support_ticket_db
      - SPRING_DATASOURCE_USERNAME=support_user
      - SPRING_DATASOURCE_PASSWORD=support_pass
    depends_on:
      - postgres

  frontend:
    build: ./support-ticket-frontend              
    ports:
      - "5173:80"                                 
    depends_on:
      - backend

volumes:
  postgres_data: